### ISSUE TITLE
disable Permission "Configure administration toolbar themes" for "Authenticated users"

### ISSUE THREAD

**Issue by bdeclerc** [openfed/openfed8#10]
I don't think this permission should be enabled for basic Auth users (or any role lower than Builder)

**Comment by stefanruijsenaars** [comment]
Hm, it's probably a mistake on our part if that's currently enabled -- that permission should have been disabled in the bundled configuration already

**Comment by rutiolma** [comment]
Fix committed. Should be ok for the next release.
