### ISSUE TITLE
Composer 2

### ISSUE THREAD

**Issue by rf-exp** [openfed/openfed8#108]
Is an update scheduled for composer 2 support?

` Problem 1
    - cweagans/composer-patches is locked to version 1.6.7 and an update of this package was not requested.
    - cweagans/composer-patches 1.6.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - drupal-composer/drupal-scaffold is locked to version 2.6.1 and an update of this package was not requested.
    - drupal-composer/drupal-scaffold 2.6.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - drupal/console-extend-plugin is locked to version 0.9.4 and an update of this package was not requested.
    - drupal/console-extend-plugin 0.9.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 4
    - oomphinc/composer-installers-extender is locked to version v1.1.2 and an update of this package was not requested.
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 5
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - w8tcha/codemirror 1.17.8 requires oomphinc/composer-installers-extender ^1.1 -> satisfiable by oomphinc/composer-installers-extender[v1.1.2].
    - w8tcha/codemirror is locked to version 1.17.8 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.`

**Comment by rutiolma** [comment]
Just committed an update to fix this issue
Openfed8 9.0 will be compatible with composer 2.0

**Comment by rutiolma** [comment]
Actually, wikimedia/composer-merge-plugin is still not compatible with composer 2.0 so it will break the Openfed8-project installation. There is a potential alternative provided at wikimedia/composer-merge-plugin > pull/189 but it requires PHP 7.2 and Openfed wasn't tested yet on that PHP version.
To be followed...

**Comment by rutiolma** [comment]
Openfed8-project 10.0-beta2 is now using wikimedia/composer-merge-plugin 2.x which makes Openfed8 10.x compatible with Composer 2.
