### ISSUE TITLE
Upgrade Kiso (基礎) base theme to latest version (2.7)

### ISSUE THREAD

**Issue by smillart** [openfed/openfed8#114]
**Drupal Kiso (基礎) base theme** new release (2.7) is now available:
https://github.com/openfed/kiso/releases/tag/2.7

* Kiso can be now included in Openfed releases compatible with D9,
* The toolbar_themes module can be dropped in favor of the Drupal core Toolbar module.

---

#### Features

* https://github.com/openfed/kiso/issues/41,
* https://github.com/openfed/kiso/issues/37,
* https://github.com/openfed/kiso/issues/35,
* https://github.com/openfed/kiso/issues/18.

#### Hot-fixes

* https://github.com/openfed/kiso/issues/45,
* https://github.com/openfed/kiso/issues/32,
* https://github.com/openfed/kiso/issues/31,
* https://github.com/openfed/kiso/issues/30,
* https://github.com/openfed/kiso/issues/29.

**Comment by rutiolma** [comment]
Added to version 8.10 - dev. It will be part of the next release.
