### ISSUE TITLE
Upgrade Kiso (基礎) base theme to latest version (2.7.2)

### ISSUE THREAD

**Issue by smillart** [openfed/openfed8#120]
**Drupal Kiso (基礎) base theme** new release (2.7.2) is now available:
https://github.com/openfed/kiso/releases/tag/2.7.2

#### Bug-fixes

* https://github.com/openfed/kiso/issues/53,
* https://github.com/openfed/kiso/issues/54,
* https://github.com/openfed/kiso/issues/55.

**Comment by rutiolma** [comment]
Openfed8 is minimally supported now, all the new developments are being done at https://github.com/openfed/openfed
Note that on Openfed 11.x we lock kiso to a minor release, allowing bug fix releases to be installed on any project when running composer update. As such, it won't be necessary to create an issue to update kiso when there's just a bug fix release.
