### ISSUE TITLE
Page manager module is missing

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#14]
We forgot to add page manager (split out of Panels, see https://www.drupal.org/project/panels):

https://www.drupal.org/project/page_manager

Discussed with the maintainers and there has been one important patch since the last release:
https://drupal.org/node/2736385

A new release should be tagged shortly.

**Comment by rutiolma** [comment]
We should include this patch https://www.drupal.org/files/issues/2820218-9.patch to solve a breadcrumb problem

**Comment by rutiolma** [comment]
Done.
