### ISSUE TITLE
Menu links cannot be translated

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#17]
Currently we cannot translate menu links (only the title/description are translatable), which is a problem as we want translations of a node to be associated with menu links in different menus (main menu EN, main menu FR, ...)

To fix this we will either have to patch core or develop a contrib module:

https://www.drupal.org/node/2858201

**Comment by rutiolma** [comment]
Suggested approach while there's no patch nor module is to cease using the menu widget in the node input screen for now and use the menu UI instead.
This was already committed to 8.1.x branch at d403354

**Comment by rutiolma** [comment]
Menu Link should be used: https://www.drupal.org/project/menu_link

**Comment by rutiolma** [comment]
@bdeclerc and @stefanruijsenaars what do you think about this one? 
Should we enable and provide a field_menulink with a default configuration for Basic Page? Perhaps it makes sense to create one main menu per language?

Note that:
- This module is useful for a multilingual site, but not needed for a single lang one.
- In a multilingual site where **all** the menu items are translated for all languages, this module can be skipped.
- There's no migration path for core menu, so this should be used from the start on a multilingual site. We should include this in the development guidelines.

**Comment by rutiolma** [comment]
The menu_link solution is being used and supported in Openfed. Closing this issue.
