### ISSUE TITLE
Base openfed8-1.0 on Drupal 8.3.0

### ISSUE THREAD

**Issue by bdeclerc** [openfed/openfed8#23]
This will put the actual release of 1.0 to "ASAP after april 5th" and allows some time for other modules to get an updated release.

For versioning, I'd like Openfed8 to mostly sync major releases to major Drupal core releases, so @8.4.0 we'd do a 2.0 release, 3.0 for 8.5.0 and so on (though keeping our options open to do our own major release between Drupal releases if justified)

**Comment by bdeclerc** [comment]
Can we update rc10 with the recent security updates and go for an rc11 followed by an actual 1.0 release?

**Comment by rutiolma** [comment]
Done.
