### ISSUE TITLE
Upgrade display suite to 8.3.x, panels to 8.4.x, and remove layout_plugin

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#26]
Panels and DS require new branches for Drupal 8.3, to make use of layout_discovery in core rather than contrib layout_plugin.

Currently these are still dev branches, but releases will be coordinated around 8.3.0 release time.

**Comment by bdeclerc** [comment]
We'll hold our 1.0 release on these modules, but this may be the kind of thing that causes headaches in the long term, especially if some dependencies don't get releases soon after a 8.x.0 Drupal Core release.

**Comment by BramG** [comment]
Seems to be fixed

**Comment by rutiolma** [comment]
Fixed since Openfed 3.x
