### ISSUE TITLE
Content editors cannnot edit menu structure and have unused links in the admin toolbar

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#3]

**Comment by stefanruijsenaars** [comment]
Fixed in https://github.com/openfed/openfed8/commit/bc85ba0b24370032996bd438500f52b728b96a2d, https://github.com/openfed/openfed8/commit/40a530faf049c4acb5af50a6940fb8cf625a8c08, https://github.com/openfed/openfed8/commit/bc85ba0b24370032996bd438500f52b728b96a2d, https://github.com/openfed/openfed8/commit/b3b5ffa12178813ea474767fcce44a38101b34bb

**Comment by bdeclerc** [comment]
Remaining issue reported separately in #10
