### ISSUE TITLE
Fatal error in installation

### ISSUE THREAD

**Issue by barthanssens** [openfed/openfed8#37]
Cloned this repo, ran composer and started installing the drupal site (PHP 7 on Debian 9, Apache 2)

Installation fails  right after installing the 82 modules

`
Drupal\\Core\\Config\\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">openfed</em> have unmet dependencies: <em class="placeholder">field.field.node.page.body (allowed_formats)</em> in /var/www/belgif8/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php on line 98 #0 /var/www/belgif8/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(469): Drupal\\Core\\Config\\UnmetDependenciesException::create('openfed', Array)\n#1 /var/www/belgif8/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\\Core\\Config\\ConfigInstaller->checkConfigurationToInstall('module', 'openfed')\n#2 /var/www/belgif8/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141): Drupal\\Core\\ProxyClass\\Config\\ConfigInstaller->checkConfigurationToInstall('module', 'openfed')\n#3 /var/www/belgif8/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#4 /var/www/belgif8/docroot/core/includes/install.core.inc(1572): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, false)\n#5 /var/www/belgif8/docroot/core/includes/install.core.inc(662): install_install_profile(Array)\n#6 /var/www/belgif8/docroot/core/includes/install.core.inc(540): install_run_task(Array, Array)\n#7 /var/www/belgif8/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)\n#8 /var/www/belgif8/docroot/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#9 {main},
`

**Comment by barthanssens** [comment]
Work-around: comment out the line `allowed_formats` in 
`profiles/contrib/openfed/config/install/field.field.node.page.body.yml`

**Comment by InPhoenityOld** [comment]
This should be fixed based on https://github.com/openfed/openfed8/commit/32288ab37e701aabe70a707677f78f016032c5e5

**Comment by rutiolma** [comment]
This issue is fixed on Openfed 4.x
