### ISSUE TITLE
Outdated Browser Message

### ISSUE THREAD

**Issue by rutiolma** [openfed/openfed8#41]
We need a solution to show a message to the users warning about an outdated browser (I guess this is a necessary due to the new european guidelines)

To do this we can use https://www.drupal.org/project/outdatedbrowser but there are some limitations (described in the module page), although there is a patch that may fix it.
This module is Seeking co-maintainer(s) so I guess this will be also a problem, unless we can help here.

Another possibility is to do a custom solution and make it available for the community.

Do you have any input regarding this?

**Comment by bdeclerc** [comment]
"I guess this is a necessary due to the new european guidelines"? I'm completely unaware of any guidelines which would make this necessary.

Why would we need this? Did you create this ticket because of some specific request from someone?

**Comment by rutiolma** [comment]
Sorry, I did a wrong assumption, this is the feedback I got from the frontend team:

> Because we stopped HTML/ CSS optimisation regarding the [Drupal 8 browser requirements](https://www.drupal.org/docs/8/system-requirements/browser-requirements) and that [Internet Explorer 9 and 10 support dropped from Drupal 8.4.x](https://www.drupal.org/node/2897971).
> 
> It is about "*Best practices*" also regarding modern Front-end development. We have to recommend users use the latest version of any browser so they can truly appreciate the work we’ve done!

**Comment by rutiolma** [comment]
This will be included in Kiso theme so I'll close the issue.
