### ISSUE TITLE
Installation instructions result in a non-functioning site?

### ISSUE THREAD

**Issue by bdeclerc** [openfed/openfed8#45]
Running
`composer create-project openfed/openfed8-project:^4.0 .  --no-interaction`
results in a "docroot" directory that contains the essential drupal directories but is missing the root files:

So I get:
`
$ ls -l

total 4

drwxr-xr-x. 14 username groupname 4096 Dec 14 14:10 core

drwxr-xr-x.  5 username groupname   55 Dec 14 14:10 libraries

drwxr-xr-x.  3 username groupname   21 Dec 14 14:10 modules

drwxr-xr-x.  3 username groupname   21 Dec 14 14:10 profiles

drwxrwxrwx.  3 username groupname   21 Dec 14 14:10 sites

drwxr-xr-x.  3 username groupname   21 Dec 14 14:10 themes

`

where I would expect:
`
$ ls -l

total 28

-rw-rw-rw-.  1 username groupname  385 Sep 18 10:28 autoload.php

drwxr-xr-x. 14 username groupname 4096 Dec 14 13:16 core

-rw-r--r--.  1 username groupname  549 Sep 18 10:28 index.php

drwxr-xr-x.  6 username groupname   74 Dec 14 13:22 libraries

drwxr-xr-x.  3 username groupname   21 Dec 14 13:16 modules

drwxr-xr-x.  3 username groupname   21 Dec 14 13:16 profiles

-rw-r--r--.  1 username groupname 1596 Sep 18 10:28 robots.txt

drwxr-xr-x.  3 username groupname  112 Aug 29 13:41 sites

drwxr-xr-x.  3 username groupname   21 Dec 14 13:16 themes

-rw-r--r--.  1 username groupname  848 Sep 18 10:28 update.php

-rw-r--r--.  1 username groupname 4555 Sep 18 10:28 web.config
`

**Comment by InPhoenityOld** [comment]
I have met this issue on a project of my own (outside Openfed context) and it seems than the scaffold doesnt't run.
My quick fix was to run manually : composer drupal-scaffold
I haven't investigate more on this issue but doesn't see anything related on issue list of Drupal-Scaffold so it can be an issue somewhere else (composer file?)

**Comment by bdeclerc** [comment]
It broke between openfed-project 1.2 and 4.0 (and since there are no openfed-project 1.3/.4/.5 releases I can't be sure if it didn't break somewhere between those.

**Comment by rutiolma** [comment]
I'm wondering how is it possible that I never have noticed this. The install procedure is the same since version 1.0.
I'll check for a fix, probably as a post-installation instruction.

**Comment by rutiolma** [comment]
Several updates were done and there are no reports referring to this anymore. 
I'm closing it for now.
