### ISSUE TITLE
Integrate image_widget_crop to OpenFed

### ISSUE THREAD

**Issue by InPhoenityOld** [openfed/openfed8#50]
Currently, OpenFed already integrate "Crop API" (https://www.drupal.org/project/crop) and "Focal Point" (https://www.drupal.org/project/focal_point).

It can be usefull to add "image_widget_crop" to the distribution to allow more precise cropping directly into the browser : https://www.drupal.org/project/image_widget_crop

What do you think ?

**Comment by bdeclerc** [comment]
I think I probably should have said yes to this several years ago :)

**Comment by rutiolma** [comment]
Added to Openfed8 8.9.x
