### ISSUE TITLE
Integrate "viewreference" to OpenFed

### ISSUE THREAD

**Issue by InPhoenityOld** [openfed/openfed8#53]
ViewReference is really usefull to inject views in node and it was previously validated for a project specific (if I'm remember right, it was for OCM). I think it is a nice candidate for inclusion.

https://www.drupal.org/project/viewsreference

What do you think ?

**Comment by rutiolma** [comment]
There's already an alternative by using twig_tweak (included in openfed)
See https://www.drupal.org/docs/8/modules/twig-tweak/cheat-sheet-8x-2x > drupal_view()

Is this enough?

**Comment by InPhoenityOld** [comment]
Well, I think we can achieve the same goal in both approaches.
However, I see one difference (but it shouldn't be a big deal because until now, this use case never happend in an OpenFed project), Views Reference is able to provide a contextual filter to the view referenced. It doesn't seems to be the case with Twig Tweak. If you think this use case will probably not occured in the future, we can go with Twig Tweak only.

**Comment by rutiolma** [comment]
Actually drupal_view() accepts arguments in the 3rd parameter so you can set any replacement tokens (including contextual filters) to use contextual filters.

**Comment by InPhoenityOld** [comment]
Oh, well, I have take a look at the code, but not the comment. Sorry. So yeah, let's go reject this ticket and use Twig Tweak only.

**Comment by rutiolma** [comment]
Dropped in favor of twig-tweak
