### ISSUE TITLE
Openfed 8.6.x doesn't install correctly

### ISSUE THREAD

**Issue by rutiolma** [openfed/openfed8#57]
There's an error when trying to create a clean installation. This should be investigated.

**Comment by InPhoenityOld** [comment]
Strange, I didn't have any issue to install 8.6. What is the error ?

**Comment by rutiolma** [comment]
You tried a clean install or an update?
I saw that error on another user PC, related with multi-language (if I'm
not mistaken), and occurred when installing the site.

This requires investigation just to be sure if there's really a bug since I
don't have more information.

Jérémie Anderlin <notifications@github.com> escreveu no dia sexta,
9/11/2018 à(s) 16:20:

**Comment by InPhoenityOld** [comment]
Hum, I am not 100% sure about if it was a clean install or an upgrade. But it seems to me it was an install. Sorry to be unable to confirm.

**Comment by rutiolma** [comment]
This was fixed in the latest beta.
