### ISSUE TITLE
Implement drag and drop support for IMCE

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#6]

**Comment by bdeclerc** [comment]
I tried drag&drop on Firefox on Linux, it allowed me to do so, but it put in this code:
`<p><img height="521" src="image/gif;base64,R0lGODlhDgAOAIAAAAAAAP///yH5BAAAAAAALAAAAAAOAA4AAAIMhI+py+0Po5y02qsKADs=" width="521" /></p>`
rather than the actual image file - though the image was uploaded as a file. (some other issues there which I'll report in another ticket)

Might be a Xubuntu issue, haven't tested it on Windows yet.

**Comment by stefanruijsenaars** [comment]
Can you test this as a content manager on RC2, and using the Flexible HTML text format?

**Comment by bdeclerc** [comment]
It works using the Flexible HTML format, perhaps default to that or even disable the other formats by default?

**Comment by stefanruijsenaars** [comment]
Doesn't the content editor/author role default to that?

**Comment by bdeclerc** [comment]
Actually spoke too soon - it works in CKEditor, but not when viewing the saved node

**Comment by bdeclerc** [comment]
Body field isn't displayed for Basic Page in rc2

**Comment by bdeclerc** [comment]
Content Editor role --> Simple HTML by default in RC2
Couldn't test Content Author role since I mistakenly selected simple workflow on install - I'll test that next.

**Comment by stefanruijsenaars** [comment]
The body is currently hidden in the display (admin/structure/types/manage/page/display), Ruben is fixing this

**Comment by bdeclerc** [comment]
Ok, enabling the openfed workflow module post-installation is taking forever, not sure if it'll happen but I'll let it run its course.

**Comment by bdeclerc** [comment]
It seems to be choking on some translation downloads, not the first time it's happened - at least it got installed.

**Comment by bdeclerc** [comment]
Can confirm : Simple HTML by default for Content Author also.

**Comment by rutiolma** [comment]
So this is the sugested order:
![image](https://cloud.githubusercontent.com/assets/5166327/23546070/418bbad2-fffe-11e6-8d6c-ebd177040cbb.png)
Flexible HTML will be the default and will be used by everyone.
Embeddable Text will also be available and it's the default for our "Embeddable" types.

We may keep "Basic HTML" but it's not really being used...

**Comment by bdeclerc** [comment]
I'd disable Basic HTML as well, I really don't see it being used a lot in practice and it'll only cause confusion. Same for Plain Text in regular content items, I've virtually never seen anyone use it.

**Comment by rutiolma** [comment]
I agree with Basic HTML, but Plain Text seems to be a fallback and, even if we don't use it regularly, it may be better to keep it.

**Comment by bdeclerc** [comment]
Well, I don't think I've *ever* seen it used on regular content types, but since we'll default to Flexible HTML and most people never change defaults, it's not a big deal to keep it.

**Comment by rutiolma** [comment]
I'll make a RC3 and this will be included there.
