### ISSUE TITLE
Include module Block Content Permissions

### ISSUE THREAD

**Issue by 4hardfire** [openfed/openfed8#84]
The usage of this module on OpenFed projects has been increased a lot and it worths having this module as part of the distribution.

See https://www.drupal.org/project/block_content_permissions.

Also include this patch https://www.drupal.org/files/issues/2018-03-17/block_content_permissions-2920739-16.patch (see issue [#2920739](https://www.drupal.org/project/block_content_permissions/issues/2920739)).

**Comment by rutiolma** [comment]
Added, disabled by default.
