### ISSUE TITLE
Errors when saving Flexible HTML text format

### ISSUE THREAD

**Issue by lramarojaona** [openfed/openfed8#86]
Hi,

I just installed Openfed 8.x-8.x-dev.
When I save the Flexible HTML text format I get the following errors which prevents me to save it.

> 
    The <drupal-entity> tag in the allowed HTML tags is missing the following attributes: data-entity-type, data-entity-uuid, data-entity-embed-display, data-entity-embed-display-settings, data-align, data-caption, data-embed-button, alt, title.
    The Display embedded entities filter needs to be placed after the following filters: Align images, Caption images, Restrict images to this site.

**Comment by rutiolma** [comment]
Updated default configs for Installation.
