### ISSUE TITLE
Upgrade twig_tweak module (8.x-2.x)

### ISSUE THREAD

**Issue by 4hardfire** [openfed/openfed8#88]
Upgrade twig_tweak module (to use version 8.x-2.x) in order to have some more functions such as **drupal_link**.

See Migration notes and changes for 8.x-1.x code to 8.x-2.x (https://www.drupal.org/docs/8/modules/twig-tweak/migrating-to-8x-2x).

**Comment by rutiolma** [comment]
I guess this will require a review of all themes before proceeding with the update, so we need to postpone it to 8.9

**Comment by rutiolma** [comment]
This shouldn't be implemented before Openfed9, because all the existing themes will have to be updated so it is a major change.

**Comment by rutiolma** [comment]
This is implemented in Openfed 8.x-10.x
Some manual actions may be required to adapt the theme before updating Openfed. A script will be included at installation time to warn about potential issues with the update.
