### ISSUE TITLE
Set Font Awesome icons (instead of SVG images) as default config for "External Links" module

### ISSUE THREAD

**Issue by smillart** [openfed/openfed8#94]
Please add the attached `extlink.settings.yml` file in the `config\install` folder. This will ensure that "External Links" contrib module ([8.x-1.2](https://www.drupal.org/project/extlink/releases/8.x-1.2)) use _Font Awesome icons_ (instead of SVG images) as default configuration for every new Openfed project.

**Zipped YML config file:** [extlink.settings.zip](https://github.com/openfed/openfed8/files/4393761/extlink.settings.zip)

**Important:** This configuration has to be used with Drupal "Kiso" (基礎) base theme **(release 2.5)** at least.

**Comment by rutiolma** [comment]
It will be available with the next release.
