### ISSUE TITLE
Replace Scheduled Updates by Scheduler

### ISSUE THREAD

**Issue by InPhoenityOld** [openfed/openfed8#96]
Scheduled Updates (https://www.drupal.org/project/scheduled_updates) doesn't seems to be maintain anymore.

It is a pretty big problem because there are some issues related to the fact than only the source language is being published. 
The current implementation does not play well with multilingual...

Because there is no progress on the issues related to this problem on D.org, we need to replace the module.

Bart suggested to use https://www.drupal.org/project/scheduler

So we need to replace in Openfed Scheduled Updates by Scheduler (and also check no Website currently using Scheduled updates).

**Comment by rutiolma** [comment]
Module added.
Also added a status message if scheduled_updates is enabled.
